# Language Server Configurations
[language-server.nil]
command = "nil"

[language-server.taplo]
command = "taplo"
args = ["lsp", "stdio"]

[language-server.vscode-css-language-server]
command = "vscode-css-language-server"
args = ["--stdio"]
config = { provideFormatter = true }

[language-server.vscode-json-language-server]
command = "vscode-json-language-server"
args = ["--stdio"]
config = { provideFormatter = true }

# Language Configurations
[[language]]
name = "nix"
auto-format = true
formatter = { command = "nixpkgs-fmt" }

[[language]]
name = "toml"
auto-format = true

[[language]]
name = "kdl"
# KDL has built-in syntax highlighting, no LSP available

[[language]]
name = "css"
auto-format = true

[[language]]
name = "json"
auto-format = true

[[language]]
name = "jsonc"
auto-format = true
